### ISSUE TITLE
Fails in Ubuntu 22.04

### ISSUE THREAD

**Issue by ManavalanG** [eWaterCycle/setup-singularity#12]
When I bumped Ubuntu version from 20.04 to 22.04, setup-singularity ran into error. 

Relevant code (shows only the select parts):

```
jobs:
  system-testing:
    name: System testing - QuaC
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.8.3
```

For the complete workflow, [see here](https://github.com/uab-cgds-worthey/quac/actions/runs/5347984712/workflow).

Relevant error:

```
Run eWaterCycle/setup-singularity@v7
Setup singularity version spec 3.8.3
Version 3.8.3 was not found in the local cache
Binary build of version 3.8.3 is not available for downloading
Downloading singularity release tarball from https://github.com/hpcng/singularity/releases/download/v3.8.3/singularity-3.8.3.tar.gz ...
Successfully downloaded singularity tarball to /home/runner/work/_temp/7aa43783-6d04-4e90-be9d-b6d800a8e574
Extracting singularity...
/usr/bin/tar xz --warning=no-unknown-keyword -C /home/runner/go/src/github.com/hpcng -f /home/runner/work/_temp/7aa43783-6d04-4e90-be9d-b6d800a8e574
Successfully extracted singularity to /home/runner/go/src/github.com/hpcng/singularity-3.8.3
Configuring in /home/runner/go/src/github.com/hpcng/singularity-3.8.3
/home/runner/go/src/github.com/hpcng/singularity-3.8.3/mconfig -p /home/runner/go/src/github.com/hpcng/singularity-3.8.3/prefix --without-suid
Configuring for project `singularity' with languages: C, Golang
=> running pre-basechecks project specific checks ...
=> running base system checks ...
 checking: host C compiler... cc
 checking: host C++ compiler... c++
 checking: host Go compiler (at least version 1.13)... not found!
mconfig: could not complete configuration
Error: The process '/home/runner/go/src/github.com/hpcng/singularity-3.8.3/mconfig' failed with exit code 1
```

For the full error message, [see here](https://github.com/uab-cgds-worthey/quac/actions/runs/5347984712/jobs/9697408786).

It [worked as expected](https://github.com/uab-cgds-worthey/quac/actions/runs/5348632569/jobs/9698751248), when I changed the ubuntu version back to 20.04.
